// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLjaB5IJ-EsB13hI6AZJxPqUv9-p6zh8M',
    appId: '1:705772017757:web:8929aa24b4dbe0df8b55b4',
    messagingSenderId: '705772017757',
    projectId: 'nairapay-49220',
    authDomain: 'nairapay-49220.firebaseapp.com',
    storageBucket: 'nairapay-49220.firebasestorage.app',
    measurementId: 'G-VR2WKN3ER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWHwOLu03nqeBT1jH5-MOohznmpDelmc',
    appId: '1:705772017757:android:2ee6eae272ead5758b55b4',
    messagingSenderId: '705772017757',
    projectId: 'nairapay-49220',
    storageBucket: 'nairapay-49220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWQDJa-l81PZhgnm0rimetloc3PTxD-k',
    appId: '1:705772017757:ios:08afbc577e081f688b55b4',
    messagingSenderId: '705772017757',
    projectId: 'nairapay-49220',
    storageBucket: 'nairapay-49220.firebasestorage.app',
    iosClientId: '705772017757-a1mfr2a42nq2ifg743etmbt1jgpnbc39.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
